// src/components/vue/DialogBase.vue
<template>
  <dialog
    ref="dialog"
    class="
      fixed left-1/2 top-1/2 z-[1000] w-[90%] max-w-[500px] -translate-x-1/2 -translate-y-1/2
      translate-y-[5vh] rounded-md border-4 border-white/10 bg-white bg-clip-padding text-sm
      leading-5 text-gray-900 opacity-0 shadow-2xl transition-[opacity,transform] duration-300
      backdrop:bg-black/50 backdrop:opacity-0 backdrop:backdrop-blur-sm
      backdrop:transition-[opacity] backdrop:duration-500
      open:translate-y-0 open:opacity-100 open:backdrop:opacity-100
    "
  >
    <h2 class="relative m-0 bg-black/25 py-5 text-center text-2xl font-bold">
      {{ title }}
      <button
        type="button"
        class="
          leading-inherit absolute right-0 top-1/2 flex aspect-square h-full -translate-y-1/2
          cursor-pointer items-center justify-center border-none bg-transparent text-gray-500
          outline-none
          hover:text-gray-200
        "
        aria-label="Close"
        @click="$emit('update:visible', false)"
      >
        <svg
          viewBox="0 0 24 24"
          class="h-4/5 w-4/5 fill-current"
        >
          <path
            d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
            fill="currentColor"
          />
        </svg>
      </button>
    </h2>
    <div class="p-4">
      <slot />
    </div>
  </dialog>
</template>

<script setup>
import { ref, watch, onMounted, nextTick } from 'vue'

const props = defineProps({
  title: {
    type: String,
    required: true
  },
  visible: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['update:visible'])

const dialog = ref(null)

onMounted(async () => {
  await nextTick()
  if (!dialog.value) return

  dialog.value.addEventListener('close', () => {
    emit('update:visible', false)
  })

  if (props.visible) {
    dialog.value.showModal()
  }
})

watch(() => props.visible, (newVisible) => {
  if (!dialog.value) return

  if (newVisible && !dialog.value.open) {
    dialog.value.showModal()
    document.body.style.overflow = 'hidden'
  } else if (!newVisible && dialog.value.open) {
    dialog.value.close()
    document.body.style.overflow = ''
  }
}, { immediate: true })
</script>

<style>
html {
  scrollbar-gutter: stable;
}
</style>

// src/components/svelte/DialogBase.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { onMount } from 'svelte';

  interface Props {
    title: string;
    visible: boolean;
  }

  let {
    title,
    visible = $bindable(),
    children,
  }: Props & { children?: () => any } = $props();

  let dialog = $state<HTMLDialogElement>();

  onMount(() => {
    if (!dialog) return;

    dialog.addEventListener('close', () => {
      visible = false;
    });

    if (visible) dialog.showModal();
  });

  $effect(() => {
    if (!dialog) return;

    if (visible && !dialog.open) {
      dialog.showModal();
    } else if (!visible && dialog.open) {
      dialog.close();
    }
  });
</script>

<dialog class="dialog-base" bind:this={dialog}>
  <h2 class="dialog-title">
    {title}
    <button
      type="button"
      class="dialog-close-btn"
      aria-label="Close"
      onclick={() => (visible = false)}
    >
      <svg viewBox="0 0 24 24"><use xlink:href="#svg-close-symbol"></use></svg>
    </button>
  </h2>

  <div class="dialog-content">
    {@render children?.()}
  </div>
</dialog>

<style>
dialog.dialog-base {
  top: 50%;
  left: 50%;
  width: 90%;
  max-width: 500px;
  font-size: 14px;
  line-height: 20px;
  background: var(--mono-f);
  color: var(--text-primary);
  box-shadow: 0 0 2rem rgba(0, 0, 0, 0.4);
  z-index: 1000;
  opacity: 0;
  border: 5px solid rgba(255, 255, 255, 0.1);
  background-clip: padding-box;
  border-radius: 5px;
  transform: translate(-50%, -50%);
  transition-property: display opacity;
  transition-duration: 0.3s;
  transition-behavior: allow-discrete;

  --vertical-shift: 5vh;
  translate: 0 var(--vertical-shift);

  &[open] {
    opacity: 1;
    translate: 0 0;

    @starting-style {
      opacity: 0;
      translate: 0 calc(var(--vertical-shift) * -1);
    }
  }
}

dialog.dialog-base::backdrop {
  opacity: 0;
  transition-property: opacity, display, overlay;
  transition-duration: 2s;
  transition-behavior: allow-discrete;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(5px);
}

dialog.dialog-base[open]::backdrop {
  opacity: 1;
}

@starting-style {
  dialog.dialog-base[open]::backdrop {
    opacity: 0;
  }
}

.dialog-close-btn {
  position: absolute;
  aspect-ratio: 1 / 1;
  height: 100%;
  top: 50%;
  right: 0;
  line-height: inherit;
  display: flex;
  align-items: center;
  justify-content: center;
  transform: translateY(-50%);
  background: transparent;
  border: none;
  color: #666;
  cursor: pointer;
  outline: none;

  svg {
    width: 80%;
    height: 80%;
    fill: currentColor;
  }

  &:hover {
    color: #f0f0f0;
  }
}

.dialog-title {
  font-size: 1.5rem;
  text-align: center;
  font-weight: bold;
  background-color: color-mix(in srgb, var(--text-primary), transparent 75%);
  padding-block: 1.25rem;
  margin: 0;
  position: relative;
}

:global {
  html {
   scrollbar-gutter: stable;
  }

  body:has(dialog[open]) {
   overflow: hidden;
  }
}
</style>
