// src/components/options/PageOptions.svelte
<svelte:options runes={true} />

<script lang="ts">
import { formatDistanceToNow } from 'date-fns';
// import { watch } from 'runed';
import browser from 'webextension-polyfill';

import * as api from '@/helpers/api';
import * as constants from '@/helpers/constants';
import { RecordsAPI } from '@/helpers/records-api';
import {
  storageGet,
  storageSet,
  storageRemove,
  getSyncedUserData,
  getSyncedOptions,
  updateSyncedOptions,
} from '@/helpers/storageUtils';
import * as utils from '@/helpers/utils';

import FormToggle from './FormToggle.svelte';

const appVersion = process.env.APP_VERSION;
const SYSTEM_API_KEY = process.env.LASTFM_API_KEY;

let isLoading = $state(true);
let saved = $state(false);
let dirty = $state(false);

const urlParams = new URLSearchParams(window.location.search);
let activeTab = $state(urlParams.get('tab') || 'modules');

let signinInProgress = $state(false);
let fallbackUsername = $state('');
const options: Partial<AddonOptions> = $state({});
let config = $state<AddonOptions>();
let userData = $state<UserData>();
let dbRecordsQty = $state<number>();
const isLoggedIn = $derived(() => !!userData?.name);
let rymSyncTimestamp = $state<number>();
let lastfmApiInputType = $state('password');
const hasApiKey = $derived(
  () => !!(options.lastfmApiKey && options.lastfmApiKey.length === 32),
);

let submitTimer: NodeJS.Timeout | null = null;

const moduleSettingsPreviews = {
  'artist-stats': [
    {
      type: 'animation',
      on: '/images/options/artist-stats-on.jpg',
      off: '/images/options/artist-stats-off.jpg',
    },
  ],
  'release-stats': [
    {
      type: 'animation',
      on: '/images/options/release-stats-on.jpg',
      off: '/images/options/release-stats-off.jpg',
    },
  ],
  'song-stats': [
    {
      type: 'animation',
      on: '/images/options/song-stats-on.jpg',
      off: '/images/options/song-stats-off.jpg',
    },
  ],
  'recent-tracks': [
    '/images/options/recent-tracks-1-playing.jpg',
    '/images/options/recent-tracks-2-playing.jpg',
    '/images/options/recent-tracks-3-playing.jpg',
    '/images/options/recent-tracks-1-stopped.jpg',
  ],
  'top-albums': [
    '/images/options/top-albums.jpg',
  ],
  'top-artists': [
    '/images/options/top-artists.jpg',
  ],
};

let activePreviewKey = $state('artist-stats');

function handleApiKeyFocus(e: Event) {
  (e.target as HTMLInputElement).select();
  lastfmApiInputType = 'text';
}

function handleApiKeyBlur(e: Event) {
  (e.target as HTMLInputElement).value = (
    e.target as HTMLInputElement
  ).value.trim();
  lastfmApiInputType = 'password';
}

async function submit() {
  const newConfig = JSON.parse(JSON.stringify(options));

  Object.keys(newConfig).forEach((key) => {
    if (config && newConfig[key] === config[key as keyof AddonOptions]) {
      delete newConfig[key];
    }
  });

  await updateSyncedOptions(newConfig);

  config = newConfig;
  saved = true;

  if (submitTimer) {
    clearTimeout(submitTimer);
  }

  submitTimer = setTimeout(() => {
    if (!dirty) {
      saved = false;
    }
  }, 3000);
  dirty = false;
}

async function reset() {
  const doConfirm = confirm('Are you sure you want to reset all settings?');
  if (!doConfirm) return;
  Object.assign(options, constants.PROFILE_OPTIONS_DEFAULT);
  await submit();
}

async function openAuthPage() {
  if (!SYSTEM_API_KEY) {
    alert('API Key is not set');
    return;
  }

  signinInProgress = true;

  try {
    const redirectUri = browser.identity.getRedirectURL();

    const authUrl = `https://www.last.fm/api/auth/?api_key=${SYSTEM_API_KEY}&cb=${encodeURIComponent(redirectUri)}`;

    const redirectUrl = await browser.identity.launchWebAuthFlow({
      url: authUrl,
      interactive: true,
    });

    const finalUrl = new URL(redirectUrl);
    const token = finalUrl.searchParams.get('token');

    if (!token) {
      throw new Error('No token returned');
    }

    const sessionKey = await utils.fetchSessionKey(token);
    if (!sessionKey) throw new Error('Invalid session key');

    const data = await api.fetchUserData(sessionKey, SYSTEM_API_KEY);

    if (!data) throw new Error('No data returned');

    const normalizedData = {
      name: data.name,
      url: data.url,
      image: data.image?.[0]?.['#text'],
    };

    userData = normalizedData;

    await storageSet({
      userData: normalizedData,
    });

    signinInProgress = false;
  } catch (err) {
    console.error('Auth failed:', err);
    signinInProgress = false;
  }
}

async function init() {
  try {
    const syncedOptions = await getSyncedOptions();
    dbRecordsQty = await RecordsAPI.getQty();

    config = syncedOptions;

    Object.assign(options, config);

    const syncedUserData = await getSyncedUserData();

    userData = syncedUserData;

    rymSyncTimestamp = await storageGet('rymSyncTimestamp', 'local');

    const debouncedSubmit = utils.debounce(() => {
      submit();
    }, 300);

    // watch(
    //   () => options,
    //   () => {
    //     saved = false;
    //     dirty = true;
    //     debouncedSubmit();
    //   },
    //   { deep: true },
    // );
    isLoading = false;
  } catch (error) {
    console.error(error);
  }
}

function openRymSync() {
  window.open('https://rateyourmusic.com/music_export?sync', '_blank');
}

async function logout() {
  const doConfirm = confirm('Are you sure you want to logout?');
  if (!doConfirm) return;
  await storageRemove('userData');
  userData = undefined;
}

const reportIssueUrl = $derived(() => {
  const baseUrl = 'https://github.com/dukhevych/rym-lastfm-stats/issues/new';

  const params = new URLSearchParams({
    template: 'bug_report.yml',
    browser: navigator.userAgent,
    'extension-version': browser.runtime.getManifest().version,
  });

  return `${baseUrl}?${params.toString()}`;
});

async function fallbackLogin() {
  const userDataRaw = await api.fetchUserDataByName(
    fallbackUsername,
    SYSTEM_API_KEY!,
  );

  if (userDataRaw) {
    const normalizedData = {
      name: userDataRaw.name,
      url: userDataRaw.url,
      image: userDataRaw.image?.[0]?.['#text'],
    };

    userData = normalizedData;

    await storageSet({
      userData: normalizedData,
    });
  }
}

// watch(
//   () => $state.snapshot(options),
//   (v, v2) => {
//     console.log('options changed');
//     console.log(JSON.stringify(v, null, 2));
//     console.log(JSON.stringify(v2, null, 2));
//   },
//   { lazy: true },
// );

init();

interface CardProps {
  isValid: boolean;
  title: string;
  validStatus: string;
  invalidStatus: string;
  action?: () => void;
  hasWarning?: boolean;
  note?: string | string[];
  isLoading?: boolean;
}
</script>

{#snippet iconKey(size = 4)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size}"
    ><path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4"
    ></path><path d="m21 2-9.6 9.6"></path><circle cx="7.5" cy="15.5" r="5.5"
    ></circle>
  </svg>
{/snippet}

{#snippet iconBarChart(size = 4)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size}"
    ><path d="M3 3v18h18"></path><path d="M18 17V9"></path><path d="M13 17V5"
    ></path><path d="M8 17v-3"></path>
  </svg>
{/snippet}

{#snippet iconClock(size = 4)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size}"
    ><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"
    ></polyline>
  </svg>
{/snippet}

{#snippet card({
  isValid,
  hasWarning = false,
  isLoading = false,
  title,
  note,
  validStatus,
  invalidStatus,
  action,
}: CardProps)}
  <svelte:element
    this={!isValid && action ? 'button' : 'div'}
    data-slot="card"
    class={[
      'text-card-foreground flex flex-col gap-6 rounded-xl py-6 border-2 text-left',
      isValid ? 'shadow-sm border-green-200 bg-green-50 dark:bg-green-900 dark:border-green-800' : '',
      !isValid ? 'border-zinc-200 bg-zinc-50 dark:bg-zinc-900 dark:border-zinc-800' : '',
      hasWarning ? 'border-yellow-200 bg-yellow-50 dark:bg-yellow-900 dark:border-yellow-800' : '',
      isLoading ? 'pointer-events-none opacity-50' : '',
      (!isValid && action) ? 'cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800' : '',
    ].join(' ')}
    onclick={!isValid && action ? action : undefined}
    role={!isValid && action ? 'button' : undefined}
  >
    <div data-slot="card-content" class="p-4">
      <div class="flex items-center gap-2">
        {#if isValid}
          {@render iconSuccess()}
        {:else}
          {@render iconError()}
        {/if}

        <div class="flex grow items-center gap-1">
          <div>
            <h3 class="font-bold">{title}</h3>
            <div class="text-sm text-gray-600 dark:text-gray-400">
              {isValid ? validStatus : invalidStatus}
            </div>
          </div>
          {#if note}
            <div class="text-xs text-gray-600 dark:text-gray-300 text-right grow flex flex-col gap-1">
              {#if typeof note === 'string'}
                {note}
              {:else}
                {#each note as n}
                  <p>{n}</p>
                {/each}
              {/if}
            </div>
          {/if}
        </div>
      </div>
    </div>
  </svelte:element>
{/snippet}

{#snippet iconSettings(size = 4)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size}"
    ><path
      d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"
    ></path><circle cx="12" cy="12" r="3"></circle>
  </svg>
{/snippet}

{#snippet iconSuccess(size = 5)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size} text-green-600"
  >
    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
    <path d="m9 11 3 3L22 4"></path>
  </svg>
{/snippet}

{#snippet iconError(size = 5)}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class="h-{size} w-{size} text-red-600"
  >
    <path d="M18 6L6 18"></path>
    <path d="M6 6l12 12"></path>
  </svg>
{/snippet}

<div
  class="min-h-viewport flex flex-col"
  style:display={isLoading ? 'none' : 'block'}
>
  <header>
    <nav class="navbar bg-base-200 shadow-sm">
      <div
        class="max-w-screen-xl mx-auto flex grow items-center justify-center py-3"
      >
        <a
          href="https://rateyourmusic.com"
          target="_blank"
          class="flex items-center gap-3"
        >
          <img src="/icons/icon48.png" alt="" />
          <h1 class="relative select-none text-2xl font-bold">
            <span
              class="absolute right-0 top-0 -translate-y-1/2 text-[10px] font-bold"
            >
              {appVersion}
              {#if constants.isDev}DEV{/if}
            </span>
            <span class="text-red-600">RYM Last.fm Stats</span>
          </h1>
        </a>
      </div>
    </nav>
  </header>
  <main class="max-w-screen-xl mx-auto w-full flex flex-col gap-3">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      {@render card({
        isValid: isLoggedIn(),
        title: 'Last.fm OAuth',
        validStatus: 'Connected',
        invalidStatus: 'Not connected',
        note: userData?.name ? [
          'Username:',
          userData.name,
        ] : undefined,
        action: openAuthPage,
        isLoading: signinInProgress,
      })}
      {@render card({
        isValid: hasApiKey(),
        title: 'API Key',
        validStatus: 'Configured',
        invalidStatus: 'Not configured',
        action: () => activeTab = 'api-auth',
      })}
      {@render card({
        isValid: !!rymSyncTimestamp,
        title: 'RYM Sync',
        validStatus: 'Completed',
        invalidStatus: 'Not completed',
        note: rymSyncTimestamp ? [
          'Last sync ' + formatDistanceToNow(rymSyncTimestamp, { addSuffix: true }),
          'Records: ' + dbRecordsQty,
        ] : [
          'No sync performed yet',
          'Records: ' + dbRecordsQty,
        ],
        action: openRymSync,
      })}
    </div>

    <div>
      <div class="tabs mx-6 tabs-lift *:flex *:items-center *:gap-2 *:grow relative">
        <a class="tab [--tab-border-color:var(--color-gray-200)] dark:[--tab-border-color:var(--color-gray-800)] {activeTab === 'modules' ? 'tab-active [--tab-bg:var(--color-gray-50)] dark:[--tab-bg:var(--color-gray-900)]' : ''}" href="#tab=modules" onclick={(e) => { e.preventDefault(); activeTab = 'modules' }}>
          {@render iconSettings()}
          Modules
        </a>
        <a class="tab [--tab-border-color:var(--color-gray-200)] dark:[--tab-border-color:var(--color-gray-800)] {activeTab === 'recent-tracks' ? 'tab-active [--tab-bg:var(--color-gray-50)] dark:[--tab-bg:var(--color-gray-900)]' : ''}" href="#tab=recent-tracks" onclick={(e) => { e.preventDefault(); activeTab = 'recent-tracks' }}>
          {@render iconClock()}
          Recent Tracks
        </a>
        <a class="tab [--tab-border-color:var(--color-gray-200)] dark:[--tab-border-color:var(--color-gray-800)] {activeTab === 'top-content' ? 'tab-active [--tab-bg:var(--color-gray-50)] dark:[--tab-bg:var(--color-gray-900)]' : ''}" href="#tab=top-content" onclick={(e) => { e.preventDefault(); activeTab = 'top-content' }}>
          {@render iconBarChart()}
          Top Content
        </a>
        <a class="tab [--tab-border-color:var(--color-gray-200)] dark:[--tab-border-color:var(--color-gray-800)] {activeTab === 'api-auth' ? 'tab-active [--tab-bg:var(--color-gray-50)] dark:[--tab-bg:var(--color-gray-900)]' : ''}" href="#tab=api-auth" onclick={(e) => { e.preventDefault(); activeTab = 'api-auth' }}>
          {@render iconKey()}
          API & Auth
        </a>
      </div>

      <div class="mt-[-1px] flex flex-col gap-3 border border-gray-200 dark:border-gray-800 rounded-xl p-4 bg-gray-50 dark:bg-gray-900" class:hidden={activeTab !== 'modules'}>
        <div class="flex items-center gap-2">
          {@render iconSettings(5)}
          <h3 class="text-lg font-semibold">Module Settings</h3>
        </div>
        <p class="text-gray-600 dark:text-gray-400">
          Enable or disable specific enhancement modules
        </p>
        <div class="flex">
          <div class="flex flex-col gap-3 w-1/3 border-r border-gray-200 dark:border-gray-800">
            <div class="flex flex-col gap-4 border-y border-l border-gray-200 dark:border-gray-800 py-4">
              <h4 class="font-medium text-gray-900 dark:text-gray-100 px-4 flex items-baseline justify-between">
                Last.fm Stats
                <span class="text-xs dark:text-blue-200 text-blue-600">
                  Updates every {utils.msToHuman(constants.STATS_CACHE_LIFETIME_GUEST_MS)}
                </span>
              </h4>
              {#if !hasApiKey() || !isLoggedIn()}
                <div class="text-xs dark:text-orange-200 text-red-600 px-4 flex flex-col gap-1">
                  {#if !hasApiKey()}
                    <p>Add a Last.fm API key to increase rate limit</p>
                  {/if}
                  {#if !isLoggedIn()}
                    <p>Connect to Last.fm to <strong>enable personal scrobbling</strong> stats</p>
                  {/if}
                </div>
              {/if}
              <div>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-4 select-none"
                  onmouseenter={() => activePreviewKey = 'artist-stats'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Artist Statistics</span>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                      Show Last.fm stats on artist pages
                    </p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-4 select-none"
                  onmouseenter={() => activePreviewKey = 'release-stats'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Release Statistics</span>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                      Show Last.fm stats on release pages
                    </p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-4 select-none"
                  onmouseenter={() => activePreviewKey = 'song-stats'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Song Statistics</span>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                      Show Last.fm stats on song pages
                    </p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked />
                </label>
              </div>
            </div>
            <div class="flex flex-col gap-4 border-y border-l border-gray-200 dark:border-gray-800 py-4 bg-gray-50 dark:bg-gray-900">
              <h4 class="font-medium text-gray-900 dark:text-gray-100 px-3 flex items-baseline justify-between">
                Profile Features
                {#if !hasApiKey()}
                  <span class="text-xs dark:text-orange-200 text-red-600">
                    ⚠️ Last.fm API key is required
                  </span>
                {/if}
              </h4>
              <div>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-3 select-none"
                  onmouseenter={() => activePreviewKey = 'recent-tracks'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Recent Tracks Widget</span>
                    <p class="text-xs text-gray-500">
                      Show recent tracks on profile
                    </p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked disabled={!hasApiKey()} />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-3 select-none"
                  onmouseenter={() => activePreviewKey = 'top-albums'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Top Albums Widget</span>
                    <p class="text-xs text-gray-500">Show top albums on profile</p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked disabled={!hasApiKey()} />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-3 select-none"
                  onmouseenter={() => activePreviewKey = 'top-artists'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Top Artists Widget</span>
                    <p class="text-xs text-gray-500">Show top artists on profile</p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked disabled={!hasApiKey()} />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 py-2 px-3 select-none"
                  onmouseenter={() => activePreviewKey = 'strict-search'}
                  onmouseleave={() => activePreviewKey = ''}
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Strict Search Results</span>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                      Enhanced search filtering
                    </p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked disabled={!hasApiKey()} />
                </label>
              </div>
            </div>
            <div class="flex flex-col gap-4 border-y border-l border-gray-200 dark:border-gray-800 py-4 bg-gray-50 dark:bg-gray-900">
              <h4 class="font-medium text-gray-900 dark:text-gray-100 px-3">
                Other Features
              </h4>
              <div>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md rounded-r-none py-2 px-3 select-none"
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">List User Ratings</span>
                    <p class="text-xs text-gray-500">Show ratings in lists</p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked />
                </label>
                <label
                  class="flex items-center justify-between cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md rounded-r-none py-2 px-3 select-none"
                >
                  <div class="flex flex-col gap-0.5">
                    <span class="text-sm font-medium">Chart User Ratings</span>
                    <p class="text-xs text-gray-500">Show ratings in charts</p>
                  </div>
                  <input type="checkbox" class="toggle toggle-primary" checked />
                </label>
              </div>
            </div>
          </div>

          <!-- Visual preview -->
          <div class="w-2/3 *:w-full *:max-w-[800px] flex items-center flex-col gap-3">
            {#each Object.entries(moduleSettingsPreviews) as [key, previews]}
              <div data-preview-key={key} class:hidden={activePreviewKey !== key}>
                {#each previews as preview}
                  {#if typeof preview === 'string'}
                    <img src={preview} alt={`Visual preview for ${key}`} />
                  {/if}
                  {#if typeof preview === 'object' && preview.type === 'animation'}
                    <div class="grid relative">
                      <img src={preview.on} alt="" class="[grid-area:1/1] animate-fadeA will-change-opacity" />
                      <img src={preview.off} alt="" class="[grid-area:1/1] animate-fadeB pointer-events-none will-change-opacity" />
                    </div>
                  {/if}
                {/each}
              </div>
            {/each}
            <!-- <img src="/images/options/top-artists.png" alt="Visual preview" />
            <img src="/images/options/top-albums.png" alt="Visual preview" />
            <img src="/images/options/recent-tracks-1-playing.png" alt="Visual preview" />
            <img src="/images/options/recent-tracks-2-playing.png" alt="Visual preview" />
            <img src="/images/options/recent-tracks-3-playing.png" alt="Visual preview" />
            <img src="/images/options/recent-tracks-1-stopped.png" alt="Visual preview" />
            <img src="/images/options/artist-stats-on.png" alt="Visual preview" />
            <img src="/images/options/artist-stats-off.png" alt="Visual preview" />
            <img src="/images/options/release-stats-on.png" alt="Visual preview" />
            <img src="/images/options/release-stats-off.png" alt="Visual preview" />
            <img src="/images/options/song-stats-on.png" alt="Visual preview" />
            <img src="/images/options/song-stats-off.png" alt="Visual preview" /> -->
          </div>
        </div>
      </div>

      <div class="space-y-6" class:hidden={activeTab !== 'recent-tracks'}>
        <div class="flex items-center gap-2 mb-4">
          {@render iconClock(5)}
          <h3 class="text-lg font-semibold">Recent Tracks</h3>
        </div>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Configure the recent tracks widget
        </p>

        <!-- <div class="flex"> -->
          <div class="flex flex-col gap-3 border border-gray-200 dark:border-gray-800">
            SETTINGS GO HERE
          </div>
        <!-- </div> -->
      </div>

      <div class="space-y-6" class:hidden={activeTab !== 'top-content'}>
        <div class="flex items-center gap-2 mb-4">
          {@render iconBarChart(5)}
          <h3 class="text-lg font-semibold">Top Content</h3>
        </div>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Configure the top content widgets
        </p>

        <div class="flex">
          <div class="flex flex-col gap-3 border-r border-gray-200 dark:border-gray-800">
            SETTINGS GO HERE
          </div>
        </div>
      </div>

      <div class="space-y-6" class:hidden={activeTab !== 'api-auth'}>
        <div class="flex items-center gap-2 mb-4">
          {@render iconKey(5)}
          <h3 class="text-lg font-semibold">API & Auth</h3>
        </div>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Configure the API and authentication settings
        </p>

        <div class="flex">
          <div class="flex flex-col gap-3 border-r border-gray-200 dark:border-gray-800">
            SETTINGS GO HERE
          </div>
        </div>
      </div>
    </div>

    <div class="flex justify-end">
      <button class="btn btn-primary">
        {@render iconSettings(5)}
        Save Configuration
      </button>
    </div>

    <!-- <form>
      <h2>Modules Turn On/Off</h2>
      <fieldset>
        {#each constants.MODULES_ARRAY as module}
          <div>
            <FormToggle bind:checked={options[module as keyof ModuleToggleConfig]} label={module} />
          </div>
        {/each}
      </fieldset>
    </form> -->
  </main>
  <!-- <div>
    <button class="btn btn-neutral">Neutral</button>
    <button class="btn btn-primary">Primary</button>
    <button class="btn btn-secondary">Secondary</button>
    <button class="btn btn-accent">Accent</button>
    <button class="btn btn-info">Info</button>
    <button class="btn btn-success">Success</button>
    <button class="btn btn-warning">Warning</button>
    <button class="btn btn-error">Error</button>
  </div> -->
</div>

<style>
/* fix for Chrome default extension font style */
:global(body) {
  font-size: inherit;
  font-family: inherit;
}

@keyframes fadeA {
  0%, 89.99% { opacity: 1; }
  90%, 100% { opacity: 0; }
}
@keyframes fadeB {
  0%, 89.99% { opacity: 0; }
  90%, 100% { opacity: 1; }
}

.animate-fadeA {
  animation: fadeA 5s infinite ease-in-out;
}
.animate-fadeB {
  animation: fadeB 5s infinite ease-in-out;
}
</style>

// src/components/options/PageOptions.vue
<template>
  <div
    id="app"
    class="min-h-viewport flex flex-col"
  >
    <header
      class="
        bg-gray-200
        dark:bg-gray-800
      "
    >
      <div class="mx-auto flex w-full max-w-[1024px] items-center justify-between px-2 py-6">
        <div class="flex items-center gap-3">
          <img
            src="/icons/icon48.png"
            alt=""
          >
          <h1 class="relative cursor-default select-none text-2xl font-bold">
            <span
              class="absolute right-0 top-0 -translate-y-1/2 text-[10px] font-bold"
            >
              {{ appVersion }}
              <template v-if="constants.isDev">DEV</template>
            </span>
            <span class="text-red-600">RYM Last.fm Stats</span>
          </h1>
        </div>
        <div class="flex items-center gap-5">
          <button
            type="button"
            class="
              font-bold
              hover:underline
            "
            @click.prevent="showModal = true"
          >
            Help
          </button>
          <a
            href="https://www.patreon.com/c/BohdanDukhevych"
            target="_blank"
            class="
              font-bold
              hover:underline
            "
          >Patreon</a>
          <a
            :href="reportIssueUrl"
            target="_blank"
            class="
              font-bold
              hover:underline
            "
          >Report issue</a>

          <div
            v-if="isLoggedIn"
            class="flex items-center gap-2"
          >
            <a
              v-if="userData.image"
              :href="userData.url"
              target="_blank"
            >
              <img
                :src="userData.image"
                alt="Last.fm Profile pic"
                class="h-8 w-8 rounded-full"
              >
            </a>
            <div>
              <strong><a
                :href="userData.url"
                target="_blank"
              >{{ userData.name }}</a></strong> (<a
                href="#"
                class="
                  text-clr-rym font-bold
                  hover:underline
                "
                @click.prevent="logout"
              >logout</a>)
            </div>
          </div>

          <div v-if="!isLoggedIn">
            <div v-if="identityApiSupported">
              <button
                class="
                  bg-clr-lastfm inline-flex min-w-[120px] items-center justify-center gap-3 rounded
                  px-4 py-2 font-bold text-white transition-colors
                  hover:bg-clr-lastfm-light
                  disabled:pointer-events-none disabled:bg-gray-400
                "
                :disabled="signinInProgress"
                @click="openAuthPage"
              >
                <template v-if="signinInProgress">
                  In progress...
                </template>
                <template v-else>
                  <!-- eslint-disable max-len -->
                  <svg
                    fill="currentColor"
                    viewBox="0 0 32 32"
                    class="h-6 w-6"
                  >
                    <path d="M14.131 22.948l-1.172-3.193c0 0-1.912 2.131-4.771 2.131-2.537 0-4.333-2.203-4.333-5.729 0-4.511 2.276-6.125 4.515-6.125 3.224 0 4.245 2.089 5.125 4.772l1.161 3.667c1.161 3.561 3.365 6.421 9.713 6.421 4.548 0 7.631-1.391 7.631-5.068 0-2.968-1.697-4.511-4.844-5.244l-2.344-0.511c-1.624-0.371-2.104-1.032-2.104-2.131 0-1.249 0.985-1.984 2.604-1.984 1.767 0 2.704 0.661 2.865 2.24l3.661-0.444c-0.297-3.301-2.584-4.656-6.323-4.656-3.308 0-6.532 1.251-6.532 5.245 0 2.5 1.204 4.077 4.245 4.807l2.484 0.589c1.865 0.443 2.484 1.224 2.484 2.287 0 1.359-1.323 1.921-3.828 1.921-3.703 0-5.244-1.943-6.124-4.625l-1.204-3.667c-1.541-4.765-4.005-6.531-8.891-6.531-5.287-0.016-8.151 3.385-8.151 9.192 0 5.573 2.864 8.595 8.005 8.595 4.14 0 6.125-1.943 6.125-1.943z" />
                  </svg>
                  <!-- eslint-enable max-len -->
                  <span>Sign in</span>
                </template>
              </button>
            </div>
            <button
              class="
                bg-clr-lastfm inline-flex min-w-[120px] items-center justify-center gap-3 rounded
                px-4 py-2 font-bold text-white transition-colors
                hover:bg-clr-lastfm-light
                disabled:pointer-events-none disabled:bg-gray-400
              "
              :disabled="signinInProgress"
              @click="openAuthPage"
            >
              <template v-if="signinInProgress">
                In progress...
              </template>
              <template v-else>
                <!-- eslint-disable max-len -->
                <svg
                  fill="currentColor"
                  viewBox="0 0 32 32"
                  class="h-6 w-6"
                >
                  <path d="M14.131 22.948l-1.172-3.193c0 0-1.912 2.131-4.771 2.131-2.537 0-4.333-2.203-4.333-5.729 0-4.511 2.276-6.125 4.515-6.125 3.224 0 4.245 2.089 5.125 4.772l1.161 3.667c1.161 3.561 3.365 6.421 9.713 6.421 4.548 0 7.631-1.391 7.631-5.068 0-2.968-1.697-4.511-4.844-5.244l-2.344-0.511c-1.624-0.371-2.104-1.032-2.104-2.131 0-1.249 0.985-1.984 2.604-1.984 1.767 0 2.704 0.661 2.865 2.24l3.661-0.444c-0.297-3.301-2.584-4.656-6.323-4.656-3.308 0-6.532 1.251-6.532 5.245 0 2.5 1.204 4.077 4.245 4.807l2.484 0.589c1.865 0.443 2.484 1.224 2.484 2.287 0 1.359-1.323 1.921-3.828 1.921-3.703 0-5.244-1.943-6.124-4.625l-1.204-3.667c-1.541-4.765-4.005-6.531-8.891-6.531-5.287-0.016-8.151 3.385-8.151 9.192 0 5.573 2.864 8.595 8.005 8.595 4.14 0 6.125-1.943 6.125-1.943z" />
                </svg>
                <!-- eslint-enable max-len -->
                <span>Sign in</span>
              </template>
            </button>
          </div>
        </div>
      </div>
    </header>

    <main class="flex flex-col px-2">
      <div class="mx-auto w-full max-w-[1024px]">
        <!-- <nav>
          <ul>
            <li>
              <a href="#" @click.prevent="switchTab('status')">Status</a>
            </li>
            <li>
              <a href="#" @click.prevent="switchTab('profile')">Profile</a>
            </li>
            <li>
              <a href="#" @click.prevent="switchTab('other')">Other</a>
            </li>
          </ul>
        </nav> -->

        <div data-tabs>
          <div data-tab="status">
            <!-- RYM SYNC -->
            <div
              class="
                mt-4 flex items-center justify-between gap-2 rounded bg-gray-200 p-4
                dark:bg-gray-800
              "
            >
              <div>
                <p>
                  <strong v-if="!rymSyncTimestamp">⚠️ RYM Sync not performed yet</strong>
                  <template v-else>
                    <strong>The latest RYM Sync was:</strong>
                    {{ formatDistanceToNow(new Date(rymSyncTimestamp), { addSuffix: true }) }}
                  </template>
                </p>
              </div>
              <div class="flex items-center gap-4">
                <span
                  class="
                    text-sm text-gray-500
                    dark:text-gray-400
                  "
                >
                  {{ dbRecordsQty }} records
                  <em v-if="!rymSyncTimestamp"><u>so far</u></em>
                </span>
                <button
                  type="button"
                  class="
                    rounded bg-orange-500 px-4 py-2 font-bold text-white
                    hover:bg-orange-700
                  "
                  :class="{
                    'bg-red-500 hover:bg-red-700': !rymSyncTimestamp,
                  }"
                  @click.prevent="openRymSync"
                >
                  <template v-if="rymSyncTimestamp">
                    Re-sync
                  </template>
                  <template v-else>
                    Run RYM Sync
                  </template>
                </button>
              </div>
            </div>
          </div>
          <!-- <div data-tab="profile">

          </div> -->
        </div>


        <!-- MANUAL LOGIN -->
        <div
          v-if="!isLoggedIn && !identityApiSupported"
          class="
            mt-4 flex flex-col items-center justify-between gap-3 rounded bg-gray-200 p-4
            dark:bg-gray-800
          "
        >
          <p
            class="
              text-sm italic text-gray-500
              dark:text-gray-300
            "
          >
            Identity API is not supported in this environment. Please enter your Last.fm username manually:
          </p>
          <input
            v-model="fallbackUsername"
            placeholder="Your Last.fm username"
            class="rounded border px-3 py-2 text-sm"
          >
          <button
            class="
              rounded bg-blue-600 px-4 py-2 font-bold text-white
              hover:bg-blue-800
            "
            @click="fallbackLogin"
          >
            Load Profile
          </button>
        </div>

        <blockquote
          class="
            mt-4 text-center text-sm text-gray-500
            dark:text-gray-400
          "
        >
          <p>
            Extension <strong>automatically</strong> tracks your RYM ratings when you rate releases on RYM release page,
            visit your own Profile page or Collection page.
          </p>
          <p>
            It's recommended to run RYM Sync periodically to keep your data up to date in case of any de-sync.
          </p>
        </blockquote>

        <form
          v-if="!loading"
          class="flex flex-col gap-5 py-5"
          @submit.prevent="submit"
        >
          <!-- MAIN SETTINGS -->
          <FormFieldset title="Last.fm API Key">
            <template #helper>
              <p>
                API Key is required for Profile enhancements and personal scrobbling stats on Artist and Release pages.
              </p>
            </template>

            <!-- LAST.FM API KEY -->
            <FormInput
              v-model="options.lastfmApiKey"
              name="lastfmApiKey"
              clearable
              placeholder="Add your lastfm API key here"
              class="font-mono"
              min="32"
              max="32"
              :type="lastfmApiInputType"
              @focus="handleApiKeyFocus"
              @blur="handleApiKeyBlur"
            >
              <template #hint>
                Used for <strong>Enhanced Profile</strong>
                and unlocks <strong>personal scrobbling stats</strong> on <strong>Artist/Release</strong> pages.
              </template>
            </FormInput>

            <div class="flex items-center justify-between gap-3">
              <a
                href="https://www.last.fm/api/account/create"
                class="
                  inline-flex min-w-[120px] justify-center rounded bg-blue-600 px-4 py-2 text-sm
                  font-bold text-white transition-colors
                  hover:bg-blue-800
                "
                target="_blank"
              >
                Create New
              </a>
              <a
                href="https://www.last.fm/api/accounts"
                class="
                  font-bold
                  hover:underline
                "
                target="_blank"
              >
                My API Keys
              </a>
            </div>
          </FormFieldset>

          <div
            v-if="!userData || !hasApiKey"
            class="flex items-center gap-3"
          >
            <!-- eslint-disable max-len -->
            <svg
              class="h-6 w-6 shrink-0"
              fill="#cc3300"
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              width="800px"
              height="800px"
              viewBox="0 0 478.125 478.125"
              xml:space="preserve"
            >
              <g>
                <g>
                  <g>
                    <circle
                      cx="239.904"
                      cy="314.721"
                      r="35.878"
                    />
                    <path
                      d="M256.657,127.525h-31.9c-10.557,0-19.125,8.645-19.125,19.125v101.975c0,10.48,8.645,19.125,19.125,19.125h31.9 c10.48,0,19.125-8.645,19.125-19.125V146.65C275.782,136.17,267.138,127.525,256.657,127.525z"
                    />
                    <path
                      d="M239.062,0C106.947,0,0,106.947,0,239.062s106.947,239.062,239.062,239.062c132.115,0,239.062-106.947,239.062-239.062 S371.178,0,239.062,0z M239.292,409.734c-94.171,0-170.595-76.348-170.595-170.596c0-94.248,76.347-170.595,170.595-170.595 s170.595,76.347,170.595,170.595C409.887,333.387,333.464,409.734,239.292,409.734z"
                    />
                  </g>
                </g>
              </g>
            </svg>
            <!-- eslint-enable max-len -->
            <p>
              To enable advanced features for your <strong>RYM Profile</strong> please
              <a
                v-if="!userData"
                href="#"
                class="
                  text-clr-rym font-bold
                  hover:underline
                "
                @click.prevent="openAuthPage"
              >sign in with Last.fm</a>
              <template v-else>
                sign in
              </template>
              and add your Last.fm API Key. You can create it by visiting <a
                href="https://www.last.fm/api/account/create"
                target="_blank"
                class="
                  text-clr-rym font-bold
                  hover:underline
                "
              >this link</a>
              (only "Application" field is required).
              If you already have an API Key, you can find it in your API Applications <a
                href="https://www.last.fm/api/accounts"
                target="_blank"
                class="
                  text-clr-rym font-bold
                  hover:underline
                "
              >here</a>.
            </p>
          </div>

          <!-- PROFILE -->
          <FormFieldset
            title="Profile"
            :disabled="!hasApiKey || !userData"
          >
            <template #helper>
              <p>
                Profile enhancements work only if you're signed in with Last.fm
              </p>
            </template>

            <!-- RECENT TRACKS -->
            <FormCheckbox
              v-model="options.profileRecentTracks"
              name="recentTracks"
              label="Recent tracks"
            />

            <!-- RECENT TRACKS LIMIT -->
            <FormRange
              v-model="options.recentTracksLimit"
              name="recentTracksLimit"
              :label="`Recent tracks limit (${constants.RECENT_TRACKS_LIMIT_MIN}-${constants.RECENT_TRACKS_LIMIT_MAX})`"
              :min="constants.RECENT_TRACKS_LIMIT_MIN"
              :max="constants.RECENT_TRACKS_LIMIT_MAX"
              :disabled="options.profileRecentTracks === false"
            />

            <FormSeparator />

            <!-- TOP ALBUMS -->
            <FormCheckbox
              v-model="options.profileTopAlbums"
              name="topAlbums"
              label="Top albums"
            />

            <FormSeparator />

            <!-- TOP ARTISTS -->
            <FormCheckbox
              v-model="options.profileTopArtists"
              name="topArtists"
              label="Top artists"
            />

            <!-- TOP ARTISTS LIMIT -->
            <FormRange
              v-model="options.topArtistsLimit"
              name="topArtistsLimit"
              :label="`Top artists limit (${constants.TOP_ARTISTS_LIMIT_MIN}-${constants.TOP_ARTISTS_LIMIT_MAX})`"
              :min="constants.TOP_ARTISTS_LIMIT_MIN"
              :max="constants.TOP_ARTISTS_LIMIT_MAX"
              :disabled="options.profileTopArtists === false"
            />
            <!--
            <div style="--hue-start: 35; --hue-end: 70">
              <div
                class="h-10 w-10"
                style="background-color: hsl(var(--hue-start), 100%, 50%)"
              />
              <div
                class="h-10 w-10"
                style="background-color: hsl(var(--hue-end), 100%, 50%)"
              />
              <div
                class="h-10"
                style="
                  background-size: 100% 100%;
                  background-image:
                    linear-gradient(to right, hsl(var(--hue-start), 100%, 50%), hsl(var(--hue-end), 100%, 50%))
                "
              />
            </div> -->

            <FormSeparator />

            <!-- RYM PLAY HISTORY HIDE -->
            <FormCheckbox
              v-model="options.rymPlayHistoryHide"
              name="rymPlayHistoryHide"
              label="Hide default 'RYM Play History' section"
            />
          </FormFieldset>

          <!-- RATINGS -->
          <FormFieldset
            title="Display my RYM Ratings"
          >
            <FormCheckbox
              v-model="options.chartsUserRating"
              name="chartRatings"
              label="Show my ratings on Charts"
            />

            <FormCheckbox
              v-model="options.listUserRating"
              name="listRatings"
              label="Show my ratings on Lists"
            />
          </FormFieldset>

          <div class="form-actions flex items-center justify-between gap-5">
            <div class="mr-auto flex items-center gap-5">
              <a
                href="#"
                class="
                  font-bold text-blue-600
                  hover:underline
                "
                @click.prevent="reset"
              >
                Reset Settings
              </a>
            </div>
            <div class="ml-auto flex items-center gap-5">
              <transition name="slide-fade">
                <div
                  v-show="saved"
                  class="text-green-700"
                >
                  <b>Saved!</b>
                </div>
              </transition>
            </div>
          </div>
        </form>
      </div>
    </main>

    <footer
      class="
        mt-auto bg-gray-100 px-2 py-4
        dark:bg-gray-800
      "
    >
      <div
        class="
          mx-auto flex w-full max-w-[700px] items-center justify-between gap-2
          *:grow *:basis-0
        "
      >
        <div>
          <a
            href="mailto:landenmetal@gmail.com"
            target="_blank"
            class="
              flex items-center gap-2 font-bold
              hover:underline
            "
          >
            <!-- eslint-disable max-len -->
            <svg
              class="h-6 w-6"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
            >
              <path d="M3.87 4h13.25C18.37 4 19 4.59 19 5.79v8.42c0 1.19-.63 1.79-1.88 1.79H3.87c-1.25 0-1.88-.6-1.88-1.79V5.79c0-1.2.63-1.79 1.88-1.79zm6.62 8.6l6.74-5.53c.24-.2.43-.66.13-1.07-.29-.41-.82-.42-1.17-.17l-5.7 3.86L4.8 5.83c-.35-.25-.88-.24-1.17.17-.3.41-.11.87.13 1.07z" />
            </svg>
            <!-- eslint-enable max-len -->
            <span>Send Feedback</span>
          </a>
        </div>
        <div class="flex justify-center gap-4">
          <a
            href="https://www.last.fm/user/Landen_13/"
            class="
              font-bold text-blue-500
              hover:underline
            "
            target="_blank"
            title="Me on Last.fm"
          >
            <img
              src="/icons/lastfm.svg"
              alt="Last.fm"
              class="block h-6 w-6"
            >
          </a>
          <a
            href="https://rateyourmusic.com/~Landen"
            class="
              font-bold text-blue-500
              hover:underline
            "
            target="_blank"
            title="Me on RYM"
          >
            <img
              src="/icons/rym.svg"
              alt="RYM"
              class="block h-6 w-6"
            >
          </a>
          <a
            href="https://open.spotify.com/user/11139279910/playlists"
            class="
              font-bold text-blue-500
              hover:underline
            "
            target="_blank"
            title="Impressive Sound playlists"
          >
            <img
              src="/icons/spotify.svg"
              alt="Spotify"
              class="block h-6 w-6"
            >
          </a>
          <a
            href="https://www.linkedin.com/in/dukhevych/"
            class="
              font-bold text-blue-500
              hover:underline
            "
            target="_blank"
            title="LinkedIn"
          >
            <img
              src="/icons/linkedin.svg"
              alt="LinkedIn"
              class="block h-6 w-6"
            >
          </a>
          <a
            href="https://github.com/dukhevych/rym-lastfm-stats"
            class="
              font-bold text-blue-500
              hover:underline
            "
            target="_blank"
            title="GitHub"
          >
            <img
              src="/icons/github.svg"
              alt="Github"
              class="block h-6 w-6"
            >
          </a>
        </div>
        <div class="text-right">
          <strong>RYM Last.fm Stats © {{ new Date().getFullYear() }}</strong>
        </div>
      </div>
    </footer>
  </div>
</template>

<script setup>
import browser from 'webextension-polyfill';
import { ref, reactive, watch, computed } from 'vue';
import { formatDistanceToNow } from 'date-fns';

// HELPERS
import { RecordsAPI } from '@/helpers/records-api';
import * as utils from '@/helpers/utils';
import * as api from '@/helpers/api';
import {
  storageGet,
  storageSet,
  storageRemove,
  getSyncedUserData,
  getSyncedOptions,
  updateSyncedOptions,
} from '@/helpers/storageUtils';
import * as constants from '@/helpers/constants';

// COMPONENTS
import FormInput from '@/components/options/FormInput.vue';
import FormCheckbox from '@/components/options/FormCheckbox.vue';
import FormFieldset from '@/components/options/FormFieldset.vue';
import FormRange from './FormRange.vue';
import FormSeparator from './FormSeparator.vue';

// ENVIRONMENT CONSTANTS
const appVersion = process.env.APP_VERSION;
const SYSTEM_API_KEY = process.env.LASTFM_API_KEY;

// FLAGS
const loading = ref(true);
const saved = ref(false);
const dirty = ref(false);
const signinInProgress = ref(false);
const showModal = ref(false);
const identityApiSupported = !!(browser.identity && browser.identity.launchWebAuthFlow);
const fallbackUsername = ref('');

// STATE
const options = reactive(Object.assign({}, constants.OPTIONS_DEFAULT));
const config = ref(null);
const userData = ref(null);
const isLoggedIn = computed(() => {
  return userData.value && userData.value.name;
});
const rymSyncTimestamp = ref(null);

const lastfmApiInputType = ref('password');

function handleApiKeyFocus(e) {
  e.target.select();
  lastfmApiInputType.value = 'text';
}

function handleApiKeyBlur(e) {
  e.target.value = e.target.value.trim();
  lastfmApiInputType.value = 'password';
}

const dbRecordsQty = ref(null);

const submit = async () => {
  const newConfig = JSON.parse(JSON.stringify(options));

  Object.keys(newConfig).forEach((key) => {
    if (newConfig[key] === config.value[key]) {
      delete newConfig[key];
    }
  });

  await updateSyncedOptions(newConfig);

  config.value = newConfig;
  saved.value = true;
  if (submit.timer) {
    clearTimeout(submit.timer);
  }
  submit.timer = setTimeout(() => {
    if (!dirty.value) {
      saved.value = false;
    }
  }, 3000);
  dirty.value = false;
};

const reset = async () => {
  const doConfirm = confirm('Are you sure you want to reset all settings?');
  if (!doConfirm) return;
  Object.assign(options, constants.PROFILE_OPTIONS_DEFAULT);
  await submit();
};

const openAuthPage = async () => {
  if (!SYSTEM_API_KEY) {
    alert('API Key is not set');
    return;
  }

  signinInProgress.value = true;

  try {
    const redirectUri = browser.identity.getRedirectURL();

    const authUrl = `https://www.last.fm/api/auth/?api_key=${SYSTEM_API_KEY}&cb=${encodeURIComponent(redirectUri)}`;

    const redirectUrl = await browser.identity.launchWebAuthFlow({
      url: authUrl,
      interactive: true
    });

    const finalUrl = new URL(redirectUrl);
    const token = finalUrl.searchParams.get("token");

    if (!token) {
      throw new Error('No token returned');
    }

    const sessionKey = await utils.fetchSessionKey(token);
    if (!sessionKey) throw new Error('Invalid session key');

    const data = await api.fetchUserData(sessionKey, SYSTEM_API_KEY);

    const normalizedData = {
      name: data.name,
      url: data.url,
      image: data.image[0]?.['#text'],
    };

    userData.value = normalizedData;

    await storageSet({
      userData: normalizedData,
    });

    signinInProgress.value = false;
  } catch (err) {
    console.error('Auth failed:', err);
    signinInProgress.value = false;
  }
};

const closeModalHandler = (e) => {
  if (e.key === 'Escape') {
    showModal.value = false;
  }
}

const init = async () => {
  try {
    const syncedOptions = await getSyncedOptions();
    dbRecordsQty.value = await RecordsAPI.getQty()

    config.value = syncedOptions;

    Object.assign(options, config.value);

    const syncedUserData = await getSyncedUserData();

    userData.value = syncedUserData;

    rymSyncTimestamp.value = await storageGet('rymSyncTimestamp', 'local');

    const debouncedSubmit = utils.debounce(() => {
      submit();
    }, 300);

    watch(
      () => options,
      () => {
        saved.value = false;
        dirty.value = true;
        debouncedSubmit();
      },
      { deep: true },
    );

    watch(
      () => showModal.value,
      () => {
        if (showModal.value) {
          document.body.style.overflow = 'hidden';
          document.addEventListener('keydown', closeModalHandler);
        } else {
          document.body.style.overflow = '';
          document.removeEventListener('keydown', closeModalHandler);
        }
      },
    )
    loading.value = false;
  } catch (error) {
    console.error(error);
  }
};

const hasApiKey = computed(() => {
  return options.lastfmApiKey && options.lastfmApiKey.length === 32;
});

const openRymSync = () => {
  window.open('https://rateyourmusic.com/music_export?sync', '_blank');
}

const logout = async () => {
  const doConfirm = confirm('Are you sure you want to logout?');
  if (!doConfirm) return;
  await storageRemove('userData');
  userData.value = null;
};

const reportIssueUrl = computed(() => {
  const baseUrl = 'https://github.com/dukhevych/rym-lastfm-stats/issues/new';

  const params = new URLSearchParams({
    template: 'bug_report.yml',
    browser: navigator.userAgent,
    'extension-version': browser.runtime.getManifest().version,
  });

  return `${baseUrl}?${params.toString()}`;
});

const fallbackLogin = async () => {
  const userDataRaw = await api.fetchUserDataByName(fallbackUsername.value, SYSTEM_API_KEY);
  if (userDataRaw) {
    const normalizedData = {
      name: userDataRaw.name,
      url: userDataRaw.url,
      image: userDataRaw.image[0]?.['#text'],
    };

    userData.value = normalizedData;

    await storageSet({
      userData: normalizedData,
    });
  }
};

init();
</script>

<style>
.slide-fade-enter-active {
  transition: all 0.15s ease-out;
}
.slide-fade-leave-active {
  transition: all 0.5s cubic-bezier(1, 0.5, 0.8, 1);
}
.slide-fade-enter-from,
.slide-fade-leave-to {
  opacity: 0;
}
.slide-fade-enter-from {
  transform: translateY(-100%);
}
.slide-fade-leave-to {
  transform: translateY(100%);
}

/* fix for Chrome default extension font style */
body {
  font-size: inherit;
  font-family: inherit;
}
</style>
